### ISSUE TITLE
Define initial search engine requirements

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetary-data-engine#1]
## 💡 Description

Define and prioritize requirements for the search engine and what we want the service to accomplish. These can be either a formal requirements doc or user stories.

Some initial thoughts:

* Search archive data (registry)
* Search archive documentation
* Search PDS online documentation (website content)
* Search by synonymous terms
* Search by features (e.g. Olympus Mons)
* Search other planetary data systems (e.g. IVOA)
* Machine-learning / training?

**Comment by jimmie** [comment]
becoming familiar w/ API, including newly deployed version by Thomas.

**Comment by tloubrieu-jpl** [comment]
@jjacob7734 will use a spreadsheet to record the requirements.

**Comment by tloubrieu-jpl** [comment]
Use as reference the user stories collected there https://airtable.com/shrvc3CFrOgqsfPlL/tblapwOzIaDVB1x3d

**Comment by jordanpadams** [comment]
User personas: https://drive.google.com/file/d/137bJHjfyjbD40r28oR1vLLOvnB_Pe_o7/view?usp=sharing

**Comment by tloubrieu-jpl** [comment]
@jjacob7734 started to analyze the user stories available to identify categories first.

**Comment by tloubrieu-jpl** [comment]
@jjacob7734 met with the SDE team

**Comment by tloubrieu-jpl** [comment]
@jjacob7734 is linking the user stories found in air table to a set of requirements for PDS search

**Comment by jordanpadams** [comment]
Status: continuing to scrub and categorize requirements

**Comment by tloubrieu-jpl** [comment]
First version should be done today.

**Comment by jjacob7734** [comment]
Completed first pass of linkage from User Stories to Search Function in the AirTable.  Would be of interest to review with the team I think.

**Comment by tloubrieu-jpl** [comment]
reviewed with the team, @jjacob7734 can you add a link to the airtable so that we can close this ticket ? Thanks

**Comment by jjacob7734** [comment]
There is a new Search Function tab in the AirTable at https://airtable.com/applgnSo7ROCVIjbd/tbl7v5DSkG5L3bZn7/viwwz6RW6xrz6BAap?blocks=bip5wd2plZQfzMzLU.  That tab has a column that indicates the User Stories that are supported by each search function.  The User Stories tab also has a new column to indicate the Search Functions that support each story.  So, the User Story / Search Function linkage is in both directions.
