### ISSUE TITLE
Add new data sources to the sinequa index

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/planetary-data-engine#6]
## 💡 Description

So that a user can search not only on datasets (as currently) but also on:
- documents
- tools
- ...

**Comment by jjacob7734** [comment]
The procedure for adding a new data source, collection, or index to Sinequa search is documented here: https://github.com/NASA-PDS/planetary-data-engine/wiki/SDE%E2%80%90Sinequa#ingesting-a-data-collection-into-sinequa
