### ISSUE TITLE
Develop Query Test Suite and Success Criteria

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetary-data-engine#7]

**Comment by tloubrieu-jpl** [comment]
@jjacob7734 need to describe more what we expect from this theme, and create sub-tickets or one analysis sub-ticket to start with.

1) We need to extract the relevant user stories to define the test suite.
2) Then for these tests, compare the expected results with the actual results from Sinequa by customizing the way each fields are search for, and some weight (boost) on each of them.

**Comment by jjacob7734** [comment]
User Stories: https://airtable.com/applgnSo7ROCVIjbd/shrvc3CFrOgqsfPlL/tblapwOzIaDVB1x3d
My summary/taxonomy of user stories: https://docs.google.com/spreadsheets/d/1qk-setU_rJ5zLv-jlrPv7ci5Wdxp2UYwt_RPgXaiS8U/edit#gid=0 (also see the `Search Function` column in the AirTable above)

**Comment by jordanpadams** [comment]
Status: @jjacob7734 looking over story categorization made early on in task. to discuss at breakout

**Comment by jjacob7734** [comment]
Notes from @jjacob7734 + @jordanpadams breakout discussion on 10/5/23:
- Faceted search refers to getting all of the unique values for a particular facet. Can we do that in Sinequa?
- Pick one of the basic keyword search user stories like #126 "Mars magnetic field" and determine the top results we want to see (relevant datasets and landing page).
- Consider scoring the actual search results to quantify how close we are to what we want.

**Comment by jjacob7734** [comment]
The following are example queries from @jordanpadams  where SDE/Sinequa does not produce the best results.  In discussion with SDE, some of these can be improved by fixing data curation problems.

**Data pages are not on top:**
1. https://sciencediscoveryengine.nasa.gov/app/nasa-sba-smd/#/search?query=%7B%22name%22:%22query-smd-primary%22,%22text%22:%22cassini%20data%22,%22tab%22:%22all%22%7D
2. https://sciencediscoveryengine.nasa.gov/app/nasa-sba-smd/#/search?query=%7B%22name%22:%22query-smd-primary%22,%22text%22:%22cassini%20data%22,%22tab%22:%22Data%22%7D

**Suboptimal duplicate pages are referenced:**

1. In https://sciencediscoveryengine.nasa.gov/app/nasa-sba-smd/#/search?query=%7B%22name%22:%22query-smd-primary%22,%22text%22:%22cassini%22,%22tab%22:%22all%22,%22select%22:%5B%5B%22treepath:%20(%60Planetary%20Image%20Galleries%60:%60%2FPlanetary%20Science%2FData%2FPlanetary%20Image%20Galleries%2F*%60)%22,%22Treepath%22%5D%5D%7D, `Planetary Image Galleries` is a subset / copy of the data that is here: https://photojournal.jpl.nasa.gov/

**Comment by jordanpadams** [comment]
Status: Investigating relevance boosting and how that can be brought into the test suite and success criteria.

**Comment by tloubrieu-jpl** [comment]
Create 2 sub-taks:
- create the test suite
- evaluate the results with metrics

**Comment by jordanpadams** [comment]
📆 October Status: Test suite software in work. On schedule

**Comment by jordanpadams** [comment]
📆 November status: Test suite software in work. On schedule

**Comment by jordanpadams** [comment]
📆 December status: In work. Completion delayed 1 sprint. No impact on delivery.

**Comment by jordanpadams** [comment]
Call this done. Also have sinequa documentation here: https://github.com/NASA-PDS/planetary-data-engine/wiki/SDE%E2%80%90Sinequa
