### ISSUE TITLE
Working with Jupyter Notebook to show various features to be used by UI team

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetary-data-engine#8]
## 💡 Description

Demonstrate access to the Sinequa planetary sandbox through the REST API in a Jupyter Notebook.  In particular, the following functionality should be demonstrated or declared to be not possible with the Sinequa REST API. 
- [x] keyword search
- [x] paging
- [x] sorting
- [x] filtering to particular tabs
- [x] filtering to particular facets
- [ ] filtering by value / logical expression

**Comment by tloubrieu-jpl** [comment]
The search will apply on PDS4 bundles and collections and PDS3 datasets. Not on observational products. As a consequence " filtering by value / logical expression" is not too relevant here.

**Comment by jjacob7734** [comment]
The notebook demonstrating the various Sinequa API capabilities is checked in to a branch at https://github.com/NASA-PDS/planetary-data-engine/blob/sinequa-api-notebook/notebooks/sinequa_api.ipynb.

**Comment by tloubrieu-jpl** [comment]
@jjacob7734 found a way to request sinequa with facets.

**Comment by tloubrieu-jpl** [comment]
We don't need the last bullet to be checked now, we can close the ticket with that. @jjacob7734 will create a pull request.

**Comment by jordanpadams** [comment]
Status: @jjacob7734 pull request to be rebased and reviewed by search team

**Comment by jordanpadams** [comment]
Status: Updates completed on PR. Issues with CI/CD found. To create new ticket.

**Comment by tloubrieu-jpl** [comment]
New ticket created for CICD https://github.com/NASA-PDS/planetary-data-engine/issues/17
