### ISSUE TITLE
Make requirement analysis & trade study for PDS Web Search

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/planetary-data-engine#9]

**Comment by jordanpadams** [comment]
@jjacob7734 created google sheet to start towards a trade study approach

**Comment by tloubrieu-jpl** [comment]
@jjacob7734 is doing more analysis on alternate search engine.

We will review the analysis criteria and options next Tuesday.

**Comment by tloubrieu-jpl** [comment]
@jjacob7734 got input on the trade study made by SMD.

**Comment by jjacob7734** [comment]
Trade study matrix (tool vs criteria): https://docs.google.com/spreadsheets/d/1dOkE7l2AzD2FE72FbP6Y3IwQ9m5qVrmeYkbQPwGt7oA/edit?usp=sharing (work in progress)

**Comment by jordanpadams** [comment]
Closing this as done for now. Jupyter notebooks are being worked on now
